

/**
 * 格式转换器
 * 职责：将文件集合转换为目标格式
 *
 * 修复：
 * P0-3: Markdown fence 自适应长度，防止嵌套反引号破坏结构
 * P1-1: 输出 skipped files manifest，用户可见哪些文件被过滤
 * P1-2: 文件排序改为纯字母序，保证每次输出完全一致（利于 prompt cache）
 */

import { OUTPUT_FORMATS, LANGUAGE_MAP, TOKEN_ESTIMATE } from '../utils/constants.js';

// ============================================
// 公共 API
// ============================================

/**
 * 转换文件集合为指定格式
 *
 * @param {Map}    files   - 过滤后的文件集合
 * @param {Object} stats   - 统计信息（来自 filter.js）
 * @param {string} format  - 输出格式
 * @param {Object} [meta]  - 附加元信息
 * @param {Array}  [meta.skipped]   - 被跳过的文件列表（来自 parser）
 * @param {string} [meta.sourceFile] - 原始 ZIP 文件名
 * @returns {string}
 */
export function convert(files, stats, format = OUTPUT_FORMATS.MARKDOWN, meta = {}) {
  if (!files || files.size === 0) {
    throw new Error('No files to convert');
  }

  // P1-2：纯字母序排序，保证每次输出顺序完全一致
  const sortedPaths = Array.from(files.keys()).sort((a, b) => a.localeCompare(b));

  switch (format) {
    case OUTPUT_FORMATS.MARKDOWN:
      return convertToMarkdown(files, sortedPaths, stats, meta);
    case OUTPUT_FORMATS.XML:
      return convertToXML(files, sortedPaths, stats, meta);
    case OUTPUT_FORMATS.TXT:
      return convertToText(files, sortedPaths, stats, meta);
    default:
      throw new Error(`Unknown format: ${format}`);
  }
}

// ============================================
// P0-3：Markdown fence 自适应长度
// ============================================

/**
 * 生成安全的 Markdown 代码块
 *
 * 原理：扫描内容中最长的连续反引号序列，
 * fence 长度比它多 1，从而永远不会被内容提前关闭。
 *
 * 示例：
 *   内容包含  → fence 用 `
 *   内容包含 ` → fence 用 ``
 *   内容不含反引号 → fence 用  （最小 3）
 *
 * @param {string} content
 * @param {string} lang
 * @returns {string}
 */
function safeMarkdownFence(content, lang = '') {
  // 找出内容中最长的连续反引号序列长度
  let maxBackticks = 2; // 从 2 开始，最终 fence 最短为 3
  const matches = content.match(/`+/g);
  if (matches) {
    for (const m of matches) {
      if (m.length > maxBackticks) maxBackticks = m.length;
    }
  }

  const fence = '`'.repeat(maxBackticks + 1);
  return `${fence}${lang}\n${content}\n${fence}`;
}

// ============================================
// P1-1：Manifest 生成
// ============================================

/**
 * 生成文件 manifest（显示哪些文件被包含、哪些被跳过及原因）
 *
 * @param {Map}    filteredFiles - 实际输出的文件
 * @param {Object} stats         - 统计信息
 * @param {Array}  skipped       - [{path, reason}]
 * @returns {string}             - Markdown 格式的 manifest 文本
 */
function buildManifest(filteredFiles, stats, skipped = []) {
  const lines = [];

  lines.push('## 📋 File Manifest\n');
  lines.push(`- **Included**: ${stats.includedFiles} files`);
  lines.push(`- **Total in ZIP**: ${stats.totalFiles} files`);

  const totalSkipped = (stats.totalFiles - stats.includedFiles);
  if (totalSkipped > 0) {
    lines.push(`- **Skipped**: ${totalSkipped} files\n`);
  } else {
    lines.push('');
  }

  // 被过滤器排除的文件（size limit / ignore pattern）
  const filterWarnings = stats.warnings.filter(w =>
    w.includes('Skipped large file') || w.includes('Total size limit')
  );
  if (filterWarnings.length > 0) {
    lines.push('### ⚠️ Filter Warnings\n');
    for (const w of filterWarnings) {
      lines.push(`- ${w}`);
    }
    lines.push('');
  }

  // 解析阶段跳过的文件（binary / read error 等）
  if (skipped.length > 0) {
    lines.push('### 🚫 Skipped by Parser\n');
    lines.push('| File | Reason |');
    lines.push('|------|--------|');
    // 最多展示 50 条，避免 manifest 过长
    const displaySkipped = skipped.slice(0, 50);
    for (const { path, reason } of displaySkipped) {
      lines.push(`| \`${escapeMarkdownCell(path)}\` | ${escapeMarkdownCell(reason)} |`);
    }
    if (skipped.length > 50) {
      lines.push(`| *(${skipped.length - 50} more not shown)* | |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function escapeMarkdownCell(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

// ============================================
// Markdown 格式
// ============================================

function convertToMarkdown(files, sortedPaths, stats, meta = {}) {
  const lines = [];
  const skipped = meta.skipped || [];

  lines.push('# 📦 Repository Content\n');
  lines.push(`> Generated by repo-compress | ${new Date().toISOString()}\n`);
  if (meta.sourceFile) {
    lines.push(`> Source: \`${meta.sourceFile}\`\n`);
  }
  lines.push('---\n');

  // 统计
  lines.push('## 📊 Statistics\n');
  lines.push(`- **Total Files**: ${stats.includedFiles}`);
  lines.push(`- **Total Size**: ${(stats.totalSize / 1024).toFixed(2)} KB`);
  lines.push(`- **Estimated Tokens**: ~${estimateTokens(stats.totalSize)} *(conservative estimate)*\n`);

  // 语言分布
  if (Object.keys(stats.languages).length > 0) {
    lines.push('### 🗂️ File Types\n');
    const sorted = Object.entries(stats.languages).sort(([, a], [, b]) => b - a);
    for (const [ext, count] of sorted) {
      lines.push(`- \`${ext || '(no ext)'}\`: ${count} file${count > 1 ? 's' : ''}`);
    }
    lines.push('');
  }

  // 非 size/total 警告（其余警告，如 context limit）
  const generalWarnings = stats.warnings.filter(w =>
    !w.includes('Skipped large file') && !w.includes('Total size limit')
  );
  if (generalWarnings.length > 0) {
    lines.push('### ⚠️ Warnings\n');
    for (const w of generalWarnings) lines.push(`- ${w}`);
    lines.push('');
  }

  lines.push('---\n');

  // P1-1：Manifest
  lines.push(buildManifest(files, stats, skipped));
  lines.push('---\n');

  // 目录树
  lines.push('## 📁 Directory Structure\n');
  // P0-3：目录树本身是普通文本，用固定 fence 即可（内容不含反引号）
  lines.push('');
  lines.push(generateTree(files));
  lines.push('\n');

  lines.push('---\n');

  // 文件内容
  lines.push('## 📄 File Contents\n');

  // P1-2：使用外部传入的 sortedPaths（纯字母序）
  for (const path of sortedPaths) {
    const file = files.get(path);
    const lang = LANGUAGE_MAP[file.extension] || '';

    lines.push(`### \`${path}\`\n`);

    // P0-3：自适应 fence，防止嵌套反引号破坏结构
    lines.push(safeMarkdownFence(file.content, lang));
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================
// XML 格式
// ============================================

function convertToXML(files, sortedPaths, stats, meta = {}) {
  const skipped = meta.skipped || [];
  const lines   = [];

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<repository>');

  // 元信息
  lines.push('  <metadata>');
  lines.push(`    <generated>${new Date().toISOString()}</generated>`);
  if (meta.sourceFile) {
    lines.push(`    <sourceFile>${escapeXml(meta.sourceFile)}</sourceFile>`);
  }
  lines.push(`    <includedFiles>${stats.includedFiles}</includedFiles>`);
  lines.push(`    <totalFiles>${stats.totalFiles}</totalFiles>`);
  lines.push(`    <totalSize>${stats.totalSize}</totalSize>`);
  lines.push(`    <estimatedTokens>${estimateTokens(stats.totalSize)}</estimatedTokens>`);
  lines.push('  </metadata>');

  // P1-1：Manifest（跳过的文件）
  if (skipped.length > 0 || stats.warnings.length > 0) {
    lines.push('  <manifest>');

    if (stats.warnings.length > 0) {
      lines.push('    <warnings>');
      for (const w of stats.warnings) {
        lines.push(`      <warning>${escapeXml(w)}</warning>`);
      }
      lines.push('    </warnings>');
    }

    if (skipped.length > 0) {
      lines.push('    <skipped>');
      for (const { path, reason } of skipped) {
        lines.push(`      <file path="${escapeXml(path)}" reason="${escapeXml(reason)}"/>`);
      }
      lines.push('    </skipped>');
    }

    lines.push('  </manifest>');
  }

  // 文件内容
  lines.push('  <files>');

  // P1-2：纯字母序
  for (const path of sortedPaths) {
    const file = files.get(path);
    lines.push(`    <file path="${escapeXml(path)}"${file.encoding ? ` encoding="${escapeXml(file.encoding)}"` : ''}>`);
    lines.push('      <content>');
    lines.push(`<![CDATA[${escapeCdata(file.content)}]]>`);
    lines.push('      </content>');
    lines.push('    </file>');
  }

  lines.push('  </files>');
  lines.push('</repository>');

  return lines.join('\n');
}

// ============================================
// 纯文本格式
// ============================================

function convertToText(files, sortedPaths, stats, meta = {}) {
  const skipped   = meta.skipped || [];
  const divider   = '='.repeat(60);
  const fileDivider = '-'.repeat(60);
  const lines     = [];

  lines.push(divider);
  lines.push('REPOSITORY CONTENT');
  lines.push(divider);
  lines.push(`Generated: ${new Date().toISOString()}`);
  if (meta.sourceFile) lines.push(`Source: ${meta.sourceFile}`);
  lines.push(`Included Files: ${stats.includedFiles} / Total: ${stats.totalFiles}`);
  lines.push(`Total Size: ${(stats.totalSize / 1024).toFixed(2)} KB`);
  lines.push(`Estimated Tokens: ~${estimateTokens(stats.totalSize)}`);
  lines.push(divider);
  lines.push('');

  // P1-1：Manifest
  if (skipped.length > 0) {
    lines.push('SKIPPED BY PARSER:');
    for (const { path, reason } of skipped.slice(0, 50)) {
      lines.push(`  [${reason}] ${path}`);
    }
    if (skipped.length > 50) lines.push(`  ...(${skipped.length - 50} more)`);
    lines.push('');
  }

  if (stats.warnings.length > 0) {
    lines.push('FILTER WARNINGS:');
    for (const w of stats.warnings) lines.push(`  - ${w}`);
    lines.push('');
  }

  lines.push(divider);
  lines.push('');

  // P1-2：纯字母序
  for (const path of sortedPaths) {
    const file = files.get(path);
    lines.push(fileDivider);
    lines.push(`FILE: ${path}`);
    if (file.encoding && file.encoding !== 'utf-8') {
      lines.push(`ENCODING: ${file.encoding}`);
    }
    lines.push(fileDivider);
    lines.push(file.content);
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================
// 目录树生成
// ============================================

/**
 * 根据文件路径集合生成目录树字符串
 * 目录排在文件前；同类型按字母序
 */
function generateTree(files) {
  const tree = {};

  for (const path of files.keys()) {
    const parts = path.split('/').filter(Boolean);
    let current = tree;

    for (let i = 0; i < parts.length; i++) {
      const part   = parts[i];
      const isFile = i === parts.length - 1;

      if (isFile) {
        current[part] = current[part] ?? null; // null 表示文件
      } else {
        if (!current[part] || current[part] === null) {
          current[part] = {};
        }
        current = current[part];
      }
    }
  }

  const lines = [];

  function render(node, indent = '') {
    const entries = Object.entries(node).sort(([aName, aVal], [bName, bVal]) => {
      const aIsDir = aVal !== null ? 1 : 0;
      const bIsDir = bVal !== null ? 1 : 0;
      if (aIsDir !== bIsDir) return bIsDir - aIsDir; // 目录优先
      return aName.localeCompare(bName);
    });

    entries.forEach(([name, children], index) => {
      const isLast      = index === entries.length - 1;
      const connector   = isLast ? '└── ' : '├── ';
      const childIndent = isLast ? '    ' : '│   ';

      lines.push(indent + connector + name);

      if (children !== null && typeof children === 'object') {
        render(children, indent + childIndent);
      }
    });
  }

  render(tree);
  return lines.join('\n');
}

// ============================================
// 工具函数
// ============================================

/**
 * Token 估算（保守：字节数 / 3）
 */
function estimateTokens(totalBytes) {
  return Math.ceil(totalBytes / 3);
}

/**
 * XML 属性值 / 元素内容转义
 */
function escapeXml(text) {
  return String(text)
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&apos;');
}

/**
 * CDATA 内容转义
 * 将 ]]> 拆分为两个 CDATA 块，防止 XML 结构损坏
 */
function escapeCdata(content) {
  return String(content).replace(/]]>/g, ']]>]]><![CDATA[');
}


