/**
 * 格式转换器
 * 职责：将文件集合转换为目标格式
 *
 * 修复记录：
 * P0-3: Markdown fence 自适应长度，防止嵌套反引号破坏结构
 * P1-1: 输出 skipped files manifest，用户可见哪些文件被过滤
 * P1-2: 文件排序改为纯字母序，保证每次输出完全一致（利于 prompt cache）
 * P0-4: 修复 escapeCdata 替换结果错误导致畸形 XML 的 bug
 * P1-3: [本次] convert 接收 cacheDetection，自动执行 BOUNDARY 物理隔离
 *        稳定文件（stable）排前，动态文件（dynamic）排后并插入物理边界墙，
 *        让 LLM Prompt Cache 命中率最大化。
 */

import { OUTPUT_FORMATS, LANGUAGE_MAP } from '../utils/constants.js';

// ============================================
// 公共 API
// ============================================

/**
 * 转换文件集合为指定格式
 *
 * @param {Map}    files          - 过滤后的文件集合
 * @param {Object} stats          - 统计信息（来自 filter.js）
 * @param {string} format         - 输出格式
 * @param {Object} [meta]         - 附加元信息
 * @param {Array}  [meta.skipped]    - 被跳过的文件列表（来自 parser）
 * @param {string} [meta.sourceFile] - 原始 ZIP 文件名
 * @param {Object} [cacheDetection] - 缓存破坏检测结果（来自 detector.js）
 *                                    有值时自动触发 BOUNDARY 物理隔离排序
 * @returns {string}
 */
export function convert(
  files,
  stats,
  format = OUTPUT_FORMATS.MARKDOWN,
  meta = {},
  cacheDetection = null,
) {
  if (!files || files.size === 0) {
    throw new Error('No files to convert');
  }

  // ── BOUNDARY 物理隔离排序 ─────────────────────────────────────────────
  // 原则：
  //   · HIGH / MEDIUM 级动态文件 → dynamicPaths（排后，破坏缓存但不影响前文）
  //   · LOW 级及无问题文件       → stablePaths（排前，可被完整命中缓存）
  //   · 两组内部各自保持纯字母序，确保每次输出顺序确定性
  //
  // 若未传入 cacheDetection（如禁用了检测），则全部视为稳定文件，
  // 行为与原有逻辑完全一致，无破坏性变更。
  // ─────────────────────────────────────────────────────────────────────

  const dynamicSet = new Set(
    (cacheDetection?.detected ?? [])
      .filter(d => d.severity === 'HIGH' || d.severity === 'MEDIUM')
      .map(d => d.path),
  );

  const stablePaths  = [];
  const dynamicPaths = [];

  for (const filePath of files.keys()) {
    if (dynamicSet.has(filePath)) dynamicPaths.push(filePath);
    else stablePaths.push(filePath);
  }

  // 纯字母序，保证内部确定性
  stablePaths.sort((a, b)  => a.localeCompare(b));
  dynamicPaths.sort((a, b) => a.localeCompare(b));

  switch (format) {
    case OUTPUT_FORMATS.MARKDOWN:
      return convertToMarkdown(files, stablePaths, dynamicPaths, stats, meta);
    case OUTPUT_FORMATS.XML:
      return convertToXML(files, stablePaths, dynamicPaths, stats, meta);
    case OUTPUT_FORMATS.TXT:
      return convertToText(files, stablePaths, dynamicPaths, stats, meta);
    default:
      throw new Error(`Unknown format: ${format}`);
  }
}

// ============================================
// P0-3：Markdown fence 自适应长度
// ============================================

/**
 * 生成安全的 Markdown 代码块
 *
 * 原理：扫描内容中最长的连续反引号序列，
 * fence 长度比它多 1，从而永远不会被内容提前关闭。
 */
function safeMarkdownFence(content, lang = '') {
  let maxBackticks = 2;
  const matches = content.match(/`+/g);
  if (matches) {
    for (const m of matches) {
      if (m.length > maxBackticks) maxBackticks = m.length;
    }
  }
  const fence = '`'.repeat(maxBackticks + 1);
  return `${fence}${lang}\n${content}\n${fence}`;
}

// ============================================
// P1-1：Manifest 生成
// ============================================

function escapeMarkdownCell(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function buildManifest(filteredFiles, stats, skipped = []) {
  const lines = [];

  lines.push('## 📋 File Manifest\n');
  lines.push(`- **Included**: ${stats.includedFiles} files`);
  lines.push(`- **Total in ZIP**: ${stats.totalFiles} files`);

  const totalSkipped = stats.totalFiles - stats.includedFiles;
  lines.push(totalSkipped > 0 ? `- **Skipped**: ${totalSkipped} files\n` : '');

  const filterWarnings = stats.warnings.filter(w =>
    w.includes('Skipped large file') || w.includes('Total size limit'),
  );
  if (filterWarnings.length > 0) {
    lines.push('### ⚠️ Filter Warnings\n');
    for (const w of filterWarnings) lines.push(`- ${w}`);
    lines.push('');
  }

  if (skipped.length > 0) {
    lines.push('### 🚫 Skipped by Parser\n');
    lines.push('| File | Reason |');
    lines.push('|------|--------|');
    const display = skipped.slice(0, 50);
    for (const { path, reason } of display) {
      lines.push(`| \`${escapeMarkdownCell(path)}\` | ${escapeMarkdownCell(reason)} |`);
    }
    if (skipped.length > 50) {
      lines.push(`| *(${skipped.length - 50} more not shown)* | |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================
// Markdown 格式
// ============================================

function convertToMarkdown(files, stablePaths, dynamicPaths, stats, meta = {}) {
  const skipped = meta.skipped || [];
  const lines   = [];

  // ── 文件头 ────────────────────────────────
  lines.push('# 📦 Repository Content\n');
  lines.push(`> Generated by repo-compress | ${new Date().toISOString()}\n`);
  if (meta.sourceFile) lines.push(`> Source: \`${meta.sourceFile}\`\n`);
  lines.push('---\n');

  // ── 统计 ──────────────────────────────────
  lines.push('## 📊 Statistics\n');
  lines.push(`- **Total Files**: ${stats.includedFiles}`);
  lines.push(`- **Total Size**: ${(stats.totalSize / 1024).toFixed(2)} KB`);
  lines.push(`- **Estimated Tokens**: ~${estimateTokens(stats.totalSize)} *(conservative estimate)*\n`);

  if (Object.keys(stats.languages).length > 0) {
    lines.push('### 🗂️ File Types\n');
    const sorted = Object.entries(stats.languages).sort(([, a], [, b]) => b - a);
    for (const [ext, count] of sorted) {
      lines.push(`- \`${ext || '(no ext)'}\`: ${count} file${count > 1 ? 's' : ''}`);
    }
    lines.push('');
  }

  const generalWarnings = stats.warnings.filter(w =>
    !w.includes('Skipped large file') && !w.includes('Total size limit'),
  );
  if (generalWarnings.length > 0) {
    lines.push('### ⚠️ Warnings\n');
    for (const w of generalWarnings) lines.push(`- ${w}`);
    lines.push('');
  }

  lines.push('---\n');
  lines.push(buildManifest(files, stats, skipped));
  lines.push('---\n');

  // ── 目录树 ────────────────────────────────
  lines.push('## 📁 Directory Structure\n');
  lines.push('');
  lines.push(generateTree(files));
  lines.push('\n');
  lines.push('---\n');

  // ── 稳定区文件内容 ────────────────────────
  lines.push('## 📄 File Contents (Stable Zone)\n');
  if (dynamicPaths.length > 0) {
    lines.push(
      '> 💡 以下文件静态稳定，内容每次相同，可被 LLM **完整缓存**（Prompt Cache）。\n',
    );
  }

  for (const filePath of stablePaths) {
    const file = files.get(filePath);
    const lang = LANGUAGE_MAP[file.extension] || '';
    lines.push(`### \`${filePath}\`\n`);
    lines.push(safeMarkdownFence(file.content, lang));
    lines.push('');
  }

  // ── 动态区文件内容（带物理边界墙）────────
  if (dynamicPaths.length > 0) {
    lines.push('');
    lines.push('<!-- ==================== BOUNDARY ==================== -->');
    lines.push('');
    lines.push('---\n');
    lines.push('## 🔄 File Contents (Dynamic Zone)\n');
    lines.push(
      '> ⚠️ 以下文件包含时间戳、UUID、哈希等**动态内容**（HIGH / MEDIUM 级），',
    );
    lines.push(
      '> 已隔离至尾部以保护前文稳定区的缓存命中率。',
    );
    lines.push(
      '> 如需完全命中缓存，请修复动态内容或通过 `--exclude` 排除这些文件。\n',
    );

    for (const filePath of dynamicPaths) {
      const file = files.get(filePath);
      const lang = LANGUAGE_MAP[file.extension] || '';
      lines.push(`### \`${filePath}\`\n`);
      lines.push(safeMarkdownFence(file.content, lang));
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ============================================
// XML 格式
// ============================================

function convertToXML(files, stablePaths, dynamicPaths, stats, meta = {}) {
  const skipped = meta.skipped || [];
  const lines   = [];

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<repository>');

  // ── 元信息 ────────────────────────────────
  lines.push('  <metadata>');
  lines.push(`    <generated>${new Date().toISOString()}</generated>`);
  if (meta.sourceFile) {
    lines.push(`    <sourceFile>${escapeXml(meta.sourceFile)}</sourceFile>`);
  }
  lines.push(`    <includedFiles>${stats.includedFiles}</includedFiles>`);
  lines.push(`    <totalFiles>${stats.totalFiles}</totalFiles>`);
  lines.push(`    <totalSize>${stats.totalSize}</totalSize>`);
  lines.push(`    <estimatedTokens>${estimateTokens(stats.totalSize)}</estimatedTokens>`);
  lines.push('  </metadata>');

  // ── Manifest ──────────────────────────────
  if (skipped.length > 0 || stats.warnings.length > 0) {
    lines.push('  <manifest>');
    if (stats.warnings.length > 0) {
      lines.push('    <warnings>');
      for (const w of stats.warnings) {
        lines.push(`      <warning>${escapeXml(w)}</warning>`);
      }
      lines.push('    </warnings>');
    }
    if (skipped.length > 0) {
      lines.push('    <skipped>');
      for (const { path, reason } of skipped) {
        lines.push(`      <file path="${escapeXml(path)}" reason="${escapeXml(reason)}"/>`);
      }
      lines.push('    </skipped>');
    }
    lines.push('  </manifest>');
  }

  // ── 稳定区 ────────────────────────────────
  const hasZones = dynamicPaths.length > 0;
  lines.push(hasZones
    ? '  <files zone="stable" note="静态稳定，可被完整缓存">'
    : '  <files>',
  );
  for (const filePath of stablePaths) {
    const file    = files.get(filePath);
    const encAttr = file.encoding ? ` encoding="${escapeXml(file.encoding)}"` : '';
    lines.push(`    <file path="${escapeXml(filePath)}"${encAttr}>`);
    lines.push('      <content>');
    lines.push(`<![CDATA[${escapeCdata(file.content)}]]>`);
    lines.push('      </content>');
    lines.push('    </file>');
  }
  lines.push('  </files>');

  // ── 动态区（带注释边界）──────────────────
  if (dynamicPaths.length > 0) {
    lines.push('');
    lines.push('  <!-- ==================== BOUNDARY ==================== -->');
    lines.push('  <!-- 以下文件包含动态内容（HIGH/MEDIUM），已隔离至尾部   -->');
    lines.push('');
    lines.push('  <files zone="dynamic" note="含动态内容，缓存命中率受限">');
    for (const filePath of dynamicPaths) {
      const file    = files.get(filePath);
      const encAttr = file.encoding ? ` encoding="${escapeXml(file.encoding)}"` : '';
      lines.push(`    <file path="${escapeXml(filePath)}"${encAttr}>`);
      lines.push('      <content>');
      lines.push(`<![CDATA[${escapeCdata(file.content)}]]>`);
      lines.push('      </content>');
      lines.push('    </file>');
    }
    lines.push('  </files>');
  }

  lines.push('</repository>');

  return lines.join('\n');
}

// ============================================
// 纯文本格式
// ============================================

function convertToText(files, stablePaths, dynamicPaths, stats, meta = {}) {
  const skipped     = meta.skipped || [];
  const divider     = '='.repeat(60);
  const fileDivider = '-'.repeat(60);
  const boundary    = '#'.repeat(60);
  const lines       = [];

  lines.push(divider);
  lines.push('REPOSITORY CONTENT');
  lines.push(divider);
  lines.push(`Generated: ${new Date().toISOString()}`);
  if (meta.sourceFile) lines.push(`Source: ${meta.sourceFile}`);
  lines.push(`Included Files: ${stats.includedFiles} / Total: ${stats.totalFiles}`);
  lines.push(`Total Size: ${(stats.totalSize / 1024).toFixed(2)} KB`);
  lines.push(`Estimated Tokens: ~${estimateTokens(stats.totalSize)}`);
  lines.push(divider);
  lines.push('');

  if (skipped.length > 0) {
    lines.push('SKIPPED BY PARSER:');
    for (const { path, reason } of skipped.slice(0, 50)) {
      lines.push(`  [${reason}] ${path}`);
    }
    if (skipped.length > 50) lines.push(`  ...(${skipped.length - 50} more)`);
    lines.push('');
  }

  if (stats.warnings.length > 0) {
    lines.push('FILTER WARNINGS:');
    for (const w of stats.warnings) lines.push(`  - ${w}`);
    lines.push('');
  }

  lines.push(divider);
  lines.push('');

  // ── 稳定区 ────────────────────────────────
  if (dynamicPaths.length > 0) {
    lines.push('STABLE ZONE - 以下文件静态稳定，可被 LLM 完整缓存');
    lines.push(divider);
    lines.push('');
  }

  for (const filePath of stablePaths) {
    const file = files.get(filePath);
    lines.push(fileDivider);
    lines.push(`FILE: ${filePath}`);
    if (file.encoding && file.encoding !== 'utf-8') {
      lines.push(`ENCODING: ${file.encoding}`);
    }
    lines.push(fileDivider);
    lines.push(file.content);
    lines.push('');
  }

  // ── 动态区 ────────────────────────────────
  if (dynamicPaths.length > 0) {
    lines.push('');
    lines.push(boundary);
    lines.push('#################### BOUNDARY ####################');
    lines.push('DYNAMIC ZONE - 以下文件含动态内容（HIGH/MEDIUM），已隔离至尾部');
    lines.push('修复或排除这些文件可让 Prompt Cache 完全命中');
    lines.push(boundary);
    lines.push('');

    for (const filePath of dynamicPaths) {
      const file = files.get(filePath);
      lines.push(fileDivider);
      lines.push(`FILE: ${filePath}`);
      if (file.encoding && file.encoding !== 'utf-8') {
        lines.push(`ENCODING: ${file.encoding}`);
      }
      lines.push(fileDivider);
      lines.push(file.content);
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ============================================
// 目录树生成
// ============================================

function generateTree(files) {
  const tree = {};

  for (const filePath of files.keys()) {
    const parts = filePath.split('/').filter(Boolean);
    let current = tree;

    for (let i = 0; i < parts.length; i++) {
      const part   = parts[i];
      const isFile = i === parts.length - 1;

      if (isFile) {
        current[part] = current[part] ?? null;
      } else {
        if (!current[part] || current[part] === null) {
          current[part] = {};
        }
        current = current[part];
      }
    }
  }

  const lines = [];

  function render(node, indent = '') {
    const entries = Object.entries(node).sort(([aN, aV], [bN, bV]) => {
      const aIsDir = aV !== null ? 1 : 0;
      const bIsDir = bV !== null ? 1 : 0;
      if (aIsDir !== bIsDir) return bIsDir - aIsDir;
      return aN.localeCompare(bN);
    });

    entries.forEach(([name, children], index) => {
      const isLast      = index === entries.length - 1;
      const connector   = isLast ? '└── ' : '├── ';
      const childIndent = isLast ? '    ' : '│   ';
      lines.push(indent + connector + name);
      if (children !== null && typeof children === 'object') {
        render(children, indent + childIndent);
      }
    });
  }

  render(tree);
  return lines.join('\n');
}

// ============================================
// 工具函数
// ============================================

/** Token 估算（保守：字节数 / 3） */
function estimateTokens(totalBytes) {
  return Math.ceil(totalBytes / 3);
}

/** XML 属性值 / 元素内容转义 */
function escapeXml(text) {
  return String(text)
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&apos;');
}

/**
 * P0-4：CDATA 内容转义（修复版）
 *
 * CDATA 块以 ]]> 结束，如果内容本身含有 ]]>，会提前关闭 CDATA。
 * 解法：把内容里的 ]]> 拆成两段 CDATA：
 *   ]]>  →  ]]>]]><![CDATA[
 *
 * 示例：
 *   原内容：  foo ]]> bar
 *   转义后：  <![CDATA[foo ]]>]]><![CDATA[ bar]]>
 *   XML解析器读到的文本：  foo ]]> bar  ✓
 */
function escapeCdata(content) {
  return String(content).replace(/]]>/g, ']]>]]><![CDATA[');
}
